#pragma once
#include "Token.h"

enum class ExpressionContext
{
	GLOBAL,
	SEQUENCE_LITERAL,
	DICTIONARY_LITERAL,
	FUNCTION_CALL,
	PARENTHESIS,
	SEQUENCE_MEMBER_ACCESS,
	COMMA_SEPARATED_EXPRESSIONS
};
